export const TOKEN = 'TOKEN'
export const ERROR_STATE = 'ERROR_STATE'
export const IS_AUTH = 'IS_AUTH'
export const JOIN_SUCCESS = 'JOIN_SUCCESS'
export const PROVINCE_LIST = 'PROVINCE_LIST'
export const CITY_LIST = 'CITY_LIST'
